--
-- made by FoxxDash/aka Ðr ÐºήgΣr & SATTY
--
-- Copyright © 2022 Imagined Menu
--

local features = require 'features'
local vehicles = require 'vehicle'
local vector3 = require 'vector3'
local f = require 'default'
local settings = f.settings
local custom_vehicles = {}
custom_vehicles.models = {
    {
        name = "Undercover Hellfire",
        {   
            parent = true,
            type = 2,
            model = 1934384720,
            handle_id = 710670,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 0,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {0, false},
                [1] = {4, false},
                [2] = {-1, false},
                [3] = {1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {0, false},
                [7] = {0, false},
                [8] = {2, false},
                [9] = {8, false},
                [10] = {-1, false},
                [11] = {3, false},
                [12] = {2, false},
                [13] = {2, false},
                [14] = {1, false},
                [15] = {3, false},
                [16] = {4, false},
                [17] = false,
                [18] = true,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {15, true},
                [24] = {-1, false},
            },
            bullet_proof_tyres = true,
            godmode = true,
            window_tint = 1,
            engine_on = true,
            freeze = false,
            collision = true,
            invisible = false,
            siren = false,
            door_lock_status = 0,
            lights = 2,
            engine_sound = "BTYPE2",
            torque = 50.0,
            horse_power = 100.0,
            dirt_level = 0.0,
            attched = false
        }, {
            parent = false,
            type = 2,
            model = 1127131465,
            handle_id = 22799,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 0,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = true,
                [1] = true,
                [2] = true,
                [3] = true,
                [4] = true,
                [5] = true,
                [6] = true
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {3, false},
                [12] = {2, false},
                [13] = {2, false},
                [14] = {-1, false},
                [15] = {3, false},
                [16] = {4, false},
                [17] = false,
                [18] = true,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {15, true},
                [24] = {-1, false}
            },
            on_rim = true,
            bullet_proof_tyres = false,
            godmode = true,
            window_tint = 1,
            engine_on = false,
            freeze = true,
            collision = false,
            invisible = false,
            siren = true,
            door_lock_status = 4,
            lights = 0,
            engine_sound = "",
            torque = 1.0,
            horse_power = 1.0,
            dirt_level = 0.0,
            attached = true,
            attachment = {
                attached_to = 710670,
                bone = 0,
                pos = {
                    x = 0,
                    y = -0.0999999866,
                    z = 0.25000003
                },
                pitch = 0,
                roll = 0,
                yaw = 0,
            }
        }
    },
    {
        name = "Police Dubsta",
        {   
            parent = true,
            type = 2,
            model = 0xe882e5f6,
            handle_id = 193551,
            colors = {
                primary = 18,
                secondary = 18,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 156,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {0, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {3, false},
                [12] = {2, false},
                [13] = {2, false},
                [14] = {0, false},
                [15] = {3, false},
                [16] = {4, false},
                [17] = false,
                [18] = true,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {15, true},
                [24] = {-1, false},
            },
            bullet_proof_tyres = true,
            godmode = true,
            window_tint = 1,
            engine_on = true,
            freeze = false,
            collision = true,
            invisible = false,
            siren = false,
            door_lock_status = 0,
            lights = 2,
            engine_sound = "DUKES2",
            torque = 50.0,
            horse_power = 100.0,
            dirt_level = 0.0,
            attched = false
        }, {
            parent = false,
            type = 2,
            model = 0xfdefaec3,
            handle_id = 178959,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 156,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {-1, false},
                [12] = {-1, false},
                [13] = {-1, false},
                [14] = {-1, false},
                [15] = {-1, false},
                [16] = {-1, false},
                [17] = false,
                [18] = false,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = false,
                [23] = {-1, false},
                [24] = {-1, false}
            },
            on_rim = true,
            bullet_proof_tyres = false,
            godmode = true,
            window_tint = 1,
            engine_on = false,
            freeze = true,
            collision = false,
            invisible = false,
            siren = true,
            door_lock_status = 4,
            lights = 0,
            engine_sound = "",
            torque = 1.0,
            horse_power = 1.0,
            dirt_level = 0.0,
            attached = true,
            attachment = {
                attached_to = 193551,
                bone = 0,
                pos = {
                    x = 0,
                    y = 0.859999895,
                    z = 0.0799999759
                },
                pitch = 0,
                roll = 0,
                yaw = -179.999985,
            }
        }, {
            parent = false,
            type = 2,
            model = 0xfdefaec3,
            handle_id = 15756,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 156,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {-1, false},
                [12] = {-1, false},
                [13] = {-1, false},
                [14] = {-1, false},
                [15] = {-1, false},
                [16] = {-1, false},
                [17] = false,
                [18] = false,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = false,
                [23] = {-1, false},
                [24] = {-1, false}
            },
            on_rim = true,
            bullet_proof_tyres = false,
            godmode = true,
            window_tint = 1,
            engine_on = false,
            freeze = true,
            collision = false,
            invisible = false,
            siren = true,
            door_lock_status = 4,
            lights = 0,
            engine_sound = "",
            torque = 1.0,
            horse_power = 1.0,
            dirt_level = 0.0,
            attached = true,
            attachment = {
                attached_to = 193551,
                bone = 0,
                pos = {
                    x = 0,
                    y = -0.949976921,
                    z = 0.749999583
                },
                pitch = -7.00000095,
                roll = -179.999985,
                yaw = 1.71661377e-05,
            }
        }
    },

    { name = "Police Tyrant",
        {   
            parent = true,
            type = 2,
            model = 0xe99011c2,
            handle_id = 716825,
            colors = {
                primary = 0,
                secondary = 0,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 1,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 255,
                b = 255
            },
            break_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {0, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {3, false},
                [12] = {2, false},
                [13] = {2, false},
                [14] = {1, false},
                [15] = {2, false},
                [16] = {4, false},
                [17] = false,
                [18] = true,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {15, true},
                [24] = {-1, false},
            },
            bullet_proof_tyres = true,
            godmode = true,
            window_tint = 1,
            engine_on = true,
            freeze = false,
            collision = true,
            invisible = false,
            siren = false,
            door_lock_status = 0,
            lights = 2,
            engine_sound = "XA21",
            torque = 50.0,
            horse_power = 100.0,
            dirt_level = 0.0,
            attched = false
        }, {
            parent = false,
            type = 2,
            model = 0x71fa16ea,
            handle_id = 706329,
            colors = {
                primary = 0,
                secondary = 0,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 156,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = true,
                [1] = true,
                [2] = true,
                [3] = true,
                [4] = true,
                [5] = true,
                [6] = true
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {-1, false},
                [12] = {-1, false},
                [13] = {-1, false},
                [14] = {-1, false},
                [15] = {-1, false},
                [16] = {4, false},
                [17] = false,
                [18] = false,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = false,
                [23] = {-1, false},
                [24] = {-1, false}
            },
            on_rim = true,
            bullet_proof_tyres = false,
            godmode = true,
            window_tint = 1,
            engine_on = false,
            freeze = true,
            collision = false,
            invisible = false,
            siren = true,
            door_lock_status = 4,
            lights = 0,
            engine_sound = "",
            torque = 1.0,
            horse_power = 1.0,
            dirt_level = 0.0,
            attached = true,
            attachment = {
                attached_to = 716825,
                bone = 0,
                pos = {
                    x = 0,
                    y = 0.230000108,
                    z = 0.220000163
                },
                pitch = 1.59000254,
                roll = 0,
                yaw = 0,
            }
        }
    },
    {
        name = "Undercover Baller LWB",
        {   
            parent = true,
            type = 2,
            model = 0x25cbe2e2,
            handle_id = 166415,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 7,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {3, false},
                [12] = {2, false},
                [13] = {2, false},
                [14] = {1, false},
                [15] = {3, false},
                [16] = {4, false},
                [17] = false,
                [18] = true,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {15, true},
                [24] = {-1, false},
            },
            bullet_proof_tyres = true,
            godmode = true,
            window_tint = 1,
            engine_on = true,
            freeze = false,
            collision = true,
            invisible = false,
            siren = false,
            door_lock_status = 0,
            lights = 2,
            engine_sound = "CLIQUE",
            torque = 50.0,
            horse_power = 100.0,
            dirt_level = 0.0,
            attched = false
        },{
            parent = false,
            type = 2,
            model = 0x432ea949,
            handle_id = 704269,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 156,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = true,
                [1] = true,
                [2] = true,
                [3] = true,
                [4] = false,
                [5] = true,
                [6] = true
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {3, false},
                [12] = {2, false},
                [13] = {2, false},
                [14] = {44, false},
                [15] = {3, false},
                [16] = {4, false},
                [17] = false,
                [18] = true,
                [19] = false,
                [20] = true,
                [21] = false,
                [22] = true,
                [23] = {49, false},
                [24] = {-1, false}
            },
            on_rim = true,
            bullet_proof_tyres = false,
            godmode = true,
            window_tint = 1,
            engine_on = false,
            freeze = true,
            collision = false,
            invisible = false,
            siren = true,
            door_lock_status = 4,
            lights = 0,
            engine_sound = "",
            torque = 1.0,
            horse_power = 1.0,
            dirt_level = 0.0,
            attached = true,
            attachment = {
                attached_to = 166415,
                bone = 0,
                pos = {
                    x = 0,
                    y = -0.190000087,
                    z = 0.0399999134
                },
                pitch = 2.38418579e-07,
                roll = 0,
                yaw = 0,
            }
        }
    },
    {
        name = "Undercover Buffalo S",
        {   
            parent = true,
            type = 2,
            model = 0x2bec3cbe,
            handle_id = 119055,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 30,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 30,
                pearl = 0,
                wheel = 7,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {0, false},
                [1] = {3, false},
                [2] = {1, false},
                [3] = {0, false},
                [4] = {4, false},
                [5] = {-1, false},
                [6] = {3, false},
                [7] = {1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {3, false},
                [12] = {2, false},
                [13] = {2, false},
                [14] = {1, false},
                [15] = {3, false},
                [16] = {4, false},
                [17] = false,
                [18] = true,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {15, true},
                [24] = {-1, false},
            },
            bullet_proof_tyres = true,
            godmode = true,
            window_tint = 1,
            engine_on = true,
            freeze = false,
            collision = true,
            invisible = false,
            siren = false,
            door_lock_status = 0,
            lights = 2,
            engine_sound = "HOTKNIFE",
            torque = 50.0,
            horse_power = 100.0,
            dirt_level = 0.0,
            attched = false
        },{
            parent = false,
            type = 2,
            model = 0x432ea949,
            handle_id = 122127,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 156,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = true,
                [1] = true,
                [2] = true,
                [3] = true,
                [4] = false,
                [5] = true,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {-1, false},
                [12] = {-1, false},
                [13] = {-1, false},
                [14] = {-1, false},
                [15] = {-1, false},
                [16] = {-1, false},
                [17] = false,
                [18] = false,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {-1, false},
                [24] = {-1, false}
            },
            on_rim = true,
            bullet_proof_tyres = false,
            godmode = true,
            window_tint = 1,
            engine_on = false,
            freeze = true,
            collision = false,
            invisible = false,
            siren = true,
            door_lock_status = 4,
            lights = 0,
            engine_sound = "",
            torque = 1.0,
            horse_power = 1.0,
            dirt_level = 0.0,
            attached = true,
            attachment = {
                attached_to = 119055,
                bone = 0,
                pos = {
                    x = 0,
                    y = 0.049999997,
                    z = 0
                },
                pitch = 0,
                roll = 0,
                yaw = 0,
            }
        }
    },
    {
        name = "Undercover Buffalo STX",
        {   
            parent = true,
            type = 2,
            model = 0xdb0c9b04,
            handle_id = 41777,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 30,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 30,
                pearl = 0,
                wheel = 7,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {0, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {4, false},
                [5] = {-1, false},
                [6] = {4, false},
                [7] = {1, false},
                [8] = {0, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {3, false},
                [12] = {2, false},
                [13] = {2, false},
                [14] = {1, false},
                [15] = {3, false},
                [16] = {4, false},
                [17] = false,
                [18] = true,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {15, true},
                [24] = {-1, false},
            },
            bullet_proof_tyres = true,
            godmode = true,
            window_tint = 1,
            engine_on = true,
            freeze = false,
            collision = true,
            invisible = false,
            siren = false,
            door_lock_status = 0,
            lights = 2,
            engine_sound = "HOTKNIFE",
            torque = 50.0,
            horse_power = 100.0,
            dirt_level = 0.0,
            attched = false
        },{
            parent = false,
            type = 2,
            model = 0x432ea949,
            handle_id = 144696,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 156,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = true,
                [1] = true,
                [2] = true,
                [3] = true,
                [4] = true,
                [5] = true,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {-1, false},
                [12] = {-1, false},
                [13] = {-1, false},
                [14] = {-1, false},
                [15] = {-1, false},
                [16] = {-1, false},
                [17] = false,
                [18] = false,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {-1, false},
                [24] = {-1, false}
            },
            on_rim = true,
            bullet_proof_tyres = false,
            godmode = true,
            window_tint = 1,
            engine_on = false,
            freeze = true,
            collision = false,
            invisible = false,
            siren = true,
            door_lock_status = 4,
            lights = 0,
            engine_sound = "",
            torque = 1.0,
            horse_power = 1.0,
            dirt_level = 0.0,
            attached = true,
            attachment = {
                attached_to = 41777,
                bone = 0,
                pos = {
                    x = 0,
                    y = -0.0799999908,
                    z = 0.0899999887
                },
                pitch = 0,
                roll = 0,
                yaw = 0,
            }
        }
    },
    {
        name = "Police Congoscenti",
        {   
            parent = true,
            type = 2,
            model = 0x360a438e,
            handle_id = 74255,
            colors = {
                primary = 0,
                secondary = 0,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 30,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 30,
                pearl = 0,
                wheel = 7,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {3, false},
                [12] = {2, false},
                [13] = {2, false},
                [14] = {1, false},
                [15] = {3, false},
                [16] = {4, false},
                [17] = false,
                [18] = true,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {15, true},
                [24] = {-1, false},
            },
            bullet_proof_tyres = true,
            godmode = true,
            window_tint = 1,
            engine_on = true,
            freeze = false,
            collision = true,
            invisible = false,
            siren = false,
            door_lock_status = 0,
            lights = 2,
            engine_sound = "VSTR",
            torque = 50.0,
            horse_power = 100.0,
            dirt_level = 0.0,
            attched = false
        },{
            parent = false,
            type = 2,
            model = 0x8a63c7b9,
            handle_id = 95247,
            colors = {
                primary = 0,
                secondary = 0,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 156,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = true,
                [1] = true,
                [2] = true,
                [3] = true,
                [4] = true,
                [5] = true,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {-1, false},
                [12] = {-1, false},
                [13] = {-1, false},
                [14] = {-1, false},
                [15] = {-1, false},
                [16] = {-1, false},
                [17] = false,
                [18] = false,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {-1, false},
                [24] = {-1, false}
            },
            on_rim = true,
            bullet_proof_tyres = false,
            godmode = true,
            window_tint = 1,
            engine_on = false,
            freeze = true,
            collision = false,
            invisible = false,
            siren = true,
            door_lock_status = 4,
            lights = 0,
            engine_sound = "",
            torque = 1.0,
            horse_power = 1.0,
            dirt_level = 0.0,
            attached = true,
            attachment = {
                attached_to = 74255,
                bone = 0,
                pos = {
                    x = 0,
                    y = -0.0699999928,
                    z = 0.0999999866
                },
                pitch = 0,
                roll = 0,
                yaw = 0,
            }
        }
    },
    {
        name = "Police Insurgent",
        {   
            parent = true,
            type = 2,
            model = 0x7b7e56f0,
            handle_id = 763918,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 152,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {3, false},
                [12] = {2, false},
                [13] = {2, false},
                [14] = {0, false},
                [15] = {3, false},
                [16] = {4, false},
                [17] = false,
                [18] = true,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {15, true},
                [24] = {-1, false},
            },
            bullet_proof_tyres = true,
            godmode = true,
            window_tint = 1,
            engine_on = true,
            freeze = false,
            collision = true,
            invisible = false,
            siren = false,
            door_lock_status = 0,
            lights = 2,
            engine_sound = "MAMBA",
            torque = 50.0,
            horse_power = 100.0,
            dirt_level = 0.0,
            attched = false
        },{
            parent = false,
            type = 2,
            model = 0x2c33b46e,
            handle_id = 427534,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 156,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = true,
                [1] = true,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {-1, false},
                [12] = {-1, false},
                [13] = {-1, false},
                [14] = {-1, false},
                [15] = {-1, false},
                [16] = {-1, false},
                [17] = false,
                [18] = false,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {-1, false},
                [24] = {-1, false}
            },
            on_rim = true,
            bullet_proof_tyres = false,
            godmode = true,
            window_tint = 1,
            engine_on = false,
            freeze = true,
            collision = false,
            invisible = false,
            siren = true,
            door_lock_status = 4,
            lights = 0,
            engine_sound = "",
            torque = 1.0,
            horse_power = 1.0,
            dirt_level = 0.0,
            attached = true,
            attachment = {
                attached_to = 763918,
                bone = 0,
                pos = {
                    x = 0,
                    y = 0.119999982,
                    z = 0.270000011
                },
                pitch = 0,
                roll = 0,
                yaw = 0,
            }
        }, {
            parent = false,
            type = 2,
            model = 0xfdefaec3,
            handle_id = 783114,
            colors = {
                primary = 111,
                secondary = 1,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 134,
                wheel = 156,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {-1, false},
                [12] = {-1, false},
                [13] = {-1, false},
                [14] = {-1, false},
                [15] = {-1, false},
                [16] = {-1, false},
                [17] = false,
                [18] = false,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = false,
                [23] = {-1, false},
                [24] = {-1, false}
            },
            on_rim = true,
            bullet_proof_tyres = false,
            godmode = true,
            window_tint = 1,
            engine_on = false,
            freeze = true,
            collision = false,
            invisible = false,
            siren = true,
            door_lock_status = 4,
            lights = 0,
            engine_sound = "",
            torque = 1.0,
            horse_power = 1.0,
            dirt_level = 0.0,
            attached = true,
            attachment = {
                attached_to = 763918,
                bone = 0,
                pos = {
                    x = 0,
                    y = -1.72000027,
                    z = 1.05999994
                },
                pitch = 1.90734863e-06,
                roll = -179.999985,
                yaw = 0,
            }
        }
    },
    {
        name = "Police Schafter V12",
        {   
            parent = true,
            type = 2,
            model = 0xa774b5a6,
            handle_id = 389646,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 156,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {1, false},
                [2] = {0, false},
                [3] = {0, false},
                [4] = {3, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {0, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {3, false},
                [12] = {2, false},
                [13] = {2, false},
                [14] = {1, false},
                [15] = {3, false},
                [16] = {4, false},
                [17] = false,
                [18] = true,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {15, true},
                [24] = {-1, false},
            },
            bullet_proof_tyres = true,
            godmode = true,
            window_tint = 1,
            engine_on = true,
            freeze = false,
            collision = true,
            invisible = false,
            siren = false,
            door_lock_status = 0,
            lights = 2,
            engine_sound = "",
            torque = 50.0,
            horse_power = 100.0,
            dirt_level = 0.0,
            attched = false
        },{
            parent = false,
            type = 2,
            model = 0x9f05f101,
            handle_id = 407822,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 156,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = "POLICE",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = true,
                [1] = true,
                [2] = true,
                [3] = true,
                [4] = false,
                [5] = true,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {-1, false},
                [12] = {-1, false},
                [13] = {-1, false},
                [14] = {-1, false},
                [15] = {-1, false},
                [16] = {-1, false},
                [17] = false,
                [18] = false,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = false,
                [23] = {-1, false},
                [24] = {-1, false}
            },
            on_rim = true,
            bullet_proof_tyres = false,
            godmode = true,
            window_tint = 1,
            engine_on = false,
            freeze = true,
            collision = false,
            invisible = false,
            siren = true,
            door_lock_status = 4,
            lights = 0,
            engine_sound = "",
            torque = 1.0,
            horse_power = 1.0,
            dirt_level = 0.0,
            attached = true,
            attachment = {
                attached_to = 389646,
                bone = 0,
                pos = {
                    x = 0,
                    y = -0.119999982,
                    z = 0.0799999908
                },
                pitch = 0,
                roll = 0,
                yaw = 0,
            }
        }
    },
    {
        name = "Ruinermill",
        {   
            parent = true,
            type = 2,
            model = 0x381e10bd,
            handle_id = 152623,
            colors = {
                primary = 160,
                secondary = 160,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 18,
                wheel = 0,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = " ",
            wheel_type = 2,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {3, false},
                [12] = {2, false},
                [13] = {2, false},
                [14] = {50, false},
                [15] = {3, false},
                [16] = {4, false},
                [17] = false,
                [18] = true,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = true,
                [23] = {72, false},
                [24] = {-1, false},
            },
            bullet_proof_tyres = true,
            godmode = true,
            window_tint = -1,
            engine_on = true,
            freeze = false,
            collision = true,
            invisible = false,
            siren = false,
            door_lock_status = 0,
            lights = 0,
            engine_sound = "",
            torque = 1.0,
            horse_power = 1.0,
            dirt_level = 0.0,
            attched = false
        },{
            parent = false,
            type = 3,
            model = 0x745f3383,
            handle_id = 26930,
            opacity = 255,
            lod_dist = 255,
            godmode = true,
            freeze = true,
            collision = true,
            invisible = false,
            attached = true,
            attachment = {
                attached_to = 152623,
                bone = 0,
                pos = {
                    x = 0,
                    y = -8.99999619,
                    z = -2.00000048
                },
                pitch = -89.9999924,
                roll = -5.7220459e-06,
                yaw = -1.33514404e-05,
            }
        },{
            parent = false,
            type = 3,
            model = 0x745f3383,
            handle_id = 41792,
            opacity = 255,
            lod_dist = 255,
            godmode = true,
            freeze = true,
            collision = true,
            invisible = false,
            attached = true,
            attachment = {
                attached_to = 152623,
                bone = 0,
                pos = {
                    x = 8.99999714,
                    y = 1.34110451e-07,
                    z = -2.00000048
                },
                pitch = -90,
                roll = -5.7220459e-06,
                yaw = 89.9999924,
            }
        },{
            parent = false,
            type = 3,
            model = 0x745f3383,
            handle_id = 46162,
            opacity = 255,
            lod_dist = 255,
            godmode = true,
            freeze = true,
            collision = true,
            invisible = false,
            attached = true,
            attachment = {
                attached_to = 152623,
                bone = 0,
                pos = {
                    x = -9.00000477,
                    y = -1.04308128e-07,
                    z = -2.00000048
                },
                pitch = -90,
                roll = -5.7220459e-06,
                yaw = -90,
            }
        },{
            parent = false,
            type = 3,
            model = 0x745f3383,
            handle_id = 110935,
            opacity = 255,
            lod_dist = 255,
            godmode = true,
            freeze = true,
            collision = true,
            invisible = false,
            attached = true,
            attachment = {
                attached_to = 152623,
                bone = 0,
                pos = {
                    x = -3.21865082e-06,
                    y = 9,
                    z = -2.00000048
                },
                pitch = -90,
                roll = -5.7220459e-06,
                yaw = -180,
            }
        }
    },
    {
        name = "Monster Raid",
        {   
            parent = true,
            type = 2,
            model = 0xcd93a7db,
            handle_id = 503637,
            colors = {
                primary = 40,
                secondary = 40,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 18,
                wheel = 0,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = " ",
            wheel_type = 4,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = false,
                [1] = false,
                [2] = true,
                [3] = true,
                [4] = true,
                [5] = false,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {-1, false},
                [12] = {-1, false},
                [13] = {-1, false},
                [14] = {-1, false},
                [15] = {-1, false},
                [16] = {-1, false},
                [17] = false,
                [18] = false,
                [19] = false,
                [20] = false,
                [21] = false,
                [22] = false,
                [23] = {8, true},
                [24] = {-1, false},
            },
            bullet_proof_tyres = true,
            godmode = true,
            window_tint = -1,
            engine_on = true,
            freeze = false,
            collision = true,
            invisible = false,
            siren = false,
            door_lock_status = 0,
            lights = 2,
            engine_sound = "",
            torque = 1.0,
            horse_power = 1.0,
            dirt_level = 0.0,
            attched = false
        }, {
            parent = false,
            type = 2,
            model = 0xd876dbe2,
            handle_id = 30807,
            colors = {
                primary = 40,
                secondary = 40,
                custom_1r = 0,
                custom_1g = 0,
                custom_1b = 0,
                custom_2r = 0,
                custom_2g = 0,
                custom_2b = 0,
                pearl = 0,
                wheel = 92,
                tyre_smoke_r = 255,
                tyre_smoke_g = 255,
                tyre_smoke_b = 255
            },
            number_plate_index = 5,
            number_plate_text = " ",
            wheel_type = 4,
            opacity = 255,
            lod_dist = 16960,
            neons = {
                left = false,
                right = false,
                front = false,
                back = false,
                r = 255,
                g = 0,
                b = 255
            },
            break_door = {
                [0] = true,
                [1] = true,
                [2] = true,
                [3] = true,
                [4] = false,
                [5] = true,
                [6] = false
            },
            open_door = {
                [0] = false,
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = false
            },
            mods = {
                [0] = {-1, false},
                [1] = {-1, false},
                [2] = {-1, false},
                [3] = {-1, false},
                [4] = {-1, false},
                [5] = {-1, false},
                [6] = {-1, false},
                [7] = {-1, false},
                [8] = {-1, false},
                [9] = {-1, false},
                [10] = {-1, false},
                [11] = {3, false},
                [12] = {2, false},
                [13] = {2, false},
                [14] = {44, false},
                [15] = {4, false},
                [16] = {4, false},
                [17] = false,
                [18] = true,
                [19] = false,
                [20] = true,
                [21] = false,
                [22] = true,
                [23] = {19, false},
                [24] = {-1, false}
            },
            on_rim = true,
            bullet_proof_tyres = false,
            godmode = true,
            window_tint = 1,
            engine_on = false,
            freeze = true,
            collision = false,
            invisible = false,
            siren = true,
            door_lock_status = 2,
            lights = 0,
            engine_sound = "",
            torque = 1.0,
            horse_power = 1.0,
            dirt_level = 0.0,
            attached = true,
            attachment = {
                attached_to = 503637,
                bone = 0,
                pos = {
                    x = -0.0271298382,
                    y = 0.428068489,
                    z = 0.665802896
                },
                pitch = 0.123927772,
                roll = 1.76272368,
                yaw = -0.928627014,
            }
        }, {
            parent = false,
            type = 3,
            model = 0x3fbdad7c,
            handle_id = 629854,
            opacity = 255,
            lod_dist = 16960,
            godmode = true,
            freeze = true,
            collision = true,
            invisible = false,
            attached = true,
            attachment = {
                attached_to = 503637,
                bone = 0,
                pos = {
                    x = 0.834497094,
                    y = -0.989804804,
                    z = 1.77926338
                },
                pitch = 0.0348004252,
                roll = -20.3995018,
                yaw = 1.37551117,
            }
        }, {
            parent = false,
            type = 3,
            model = 0xde657a3f,
            handle_id = 400485,
            opacity = 255,
            lod_dist = 16960,
            godmode = true,
            freeze = true,
            collision = true,
            invisible = false,
            attached = true,
            attachment = {
                attached_to = 503637,
                bone = 0,
                pos = {
                    x = -0.00628418196,
                    y = -1.18708086,
                    z = 1.64442086
                },
                pitch = 0.0348004252,
                roll = -0.399528533,
                yaw = -0.744163513,
            }
        },{
            parent = false,
            type = 3,
            model = 0xe2174d98,
            handle_id = 105577,
            opacity = 255,
            lod_dist = 255,
            godmode = true,
            freeze = true,
            collision = true,
            invisible = false,
            attached = true,
            attachment = {
                attached_to = 503637,
                bone = 0,
                pos = {
                    x = 0.00973733515,
                    y = -2.25562787,
                    z = 1.93469644
                },
                pitch = 0.0348004252,
                roll = -0.399528533,
                yaw = -1.61295319,
            }
        }
    },
}

local spawned = 0
local new_request = {}
function custom_vehicles.request(CustomVehicle)   
    for _, v in ipairs(CustomVehicle)
    do
        local loaded, hash = features.request_model(v.model)
        if not hash then return -1 end
        if loaded == 0 then return 0 end
    end
    return 1
end

function custom_vehicles.unload(CustomVehicle)   
    for _, v in ipairs(CustomVehicle)
    do
        STREAMING.SET_MODEL_AS_NO_LONGER_NEEDED(v.model)
    end
    return true
end

function custom_vehicles.spawn(CustomVehicle, spawn_i, pos, id)
    if new_request[spawn_i][CustomVehicle.handle_id] then return end
    local ent
    if CustomVehicle.type == 2 then
        ent = entities.create_vehicle(CustomVehicle.model, pos)
    elseif CustomVehicle.type == 3 then
        ent = entities.create_object(CustomVehicle.model, pos)
        NETWORK.SET_NETWORK_ID_EXISTS_ON_ALL_MACHINES(NETWORK.NETWORK_GET_NETWORK_ID_FROM_ENTITY(ent), true)
        NETWORK._NETWORK_SET_ENTITY_INVISIBLE_TO_NETWORK(ent, false)
    end
    if not new_request[spawn_i].parent and CustomVehicle.parent then
        new_request[spawn_i].parent = ent
    end
    new_request[spawn_i][CustomVehicle.handle_id] = ent
    if CustomVehicle.type == 2 then
        DECORATOR.DECOR_SET_INT(ent, "MPBitset", 1024)
        VEHICLE.SET_VEHICLE_MOD_KIT(ent, 0)
        vehicles.repair(ent)
        vehicles.set_godmode(ent, CustomVehicle.godmode)
        VEHICLE.SET_VEHICLE_COLOURS(ent, CustomVehicle.colors.primary, CustomVehicle.colors.secondary)
        VEHICLE.SET_VEHICLE_CUSTOM_PRIMARY_COLOUR(ent, CustomVehicle.colors.custom_1r, CustomVehicle.colors.custom_1g, CustomVehicle.colors.custom_1b)
        VEHICLE.SET_VEHICLE_CUSTOM_SECONDARY_COLOUR(ent, CustomVehicle.colors.custom_2r, CustomVehicle.colors.custom_2g, CustomVehicle.colors.custom_2b)
        VEHICLE.SET_VEHICLE_EXTRA_COLOURS(ent, CustomVehicle.colors.pearl, CustomVehicle.colors.wheel)
        VEHICLE.SET_VEHICLE_TYRE_SMOKE_COLOR(ent , CustomVehicle.colors.tyre_smoke_r, CustomVehicle.colors.tyre_smoke_g, CustomVehicle.colors.tyre_smoke_b)
        VEHICLE.SET_VEHICLE_NUMBER_PLATE_TEXT_INDEX(ent, CustomVehicle.number_plate_index)
        VEHICLE.SET_VEHICLE_NUMBER_PLATE_TEXT(ent, CustomVehicle.number_plate_text)
        VEHICLE.SET_VEHICLE_WHEEL_TYPE(ent, CustomVehicle.wheel_type)
        if engine_sound ~= '' then
            AUDIO._FORCE_VEHICLE_ENGINE_AUDIO(ent, CustomVehicle.engine_sound)
        end
        for i = 0, 24
        do
            if i < 17 or i > 22 and CustomVehicle.mods[i][1] ~= -1 then
                VEHICLE.SET_VEHICLE_MOD(ent, i, CustomVehicle.mods[i][1], CustomVehicle.mods[i][2])
            else
                VEHICLE.TOGGLE_VEHICLE_MOD(ent, i, CustomVehicle.mods[i])
            end
        end

        VEHICLE.SET_VEHICLE_TYRES_CAN_BURST(ent, not CustomVehicle.bullet_proof_tyres)
        if CustomVehicle.on_rim then
            for i = 0, 5 do
              VEHICLE.SET_VEHICLE_TYRE_BURST(ent, i, true, 1000.0)
            end
        end
        VEHICLE._SET_VEHICLE_NEON_LIGHTS_COLOUR(ent, CustomVehicle.neons.r, CustomVehicle.neons.g, CustomVehicle.neons.b)
        VEHICLE._SET_VEHICLE_NEON_LIGHT_ENABLED(ent, 0, CustomVehicle.neons.left)
        VEHICLE._SET_VEHICLE_NEON_LIGHT_ENABLED(ent, 1, CustomVehicle.neons.right)
        VEHICLE._SET_VEHICLE_NEON_LIGHT_ENABLED(ent, 2, CustomVehicle.neons.front)
        VEHICLE._SET_VEHICLE_NEON_LIGHT_ENABLED(ent, 3, CustomVehicle.neons.back)
        VEHICLE.SET_VEHICLE_WINDOW_TINT(ent, CustomVehicle.window_tint)
        VEHICLE.SET_VEHICLE_ENGINE_ON(ent, CustomVehicle.engine_on, true, false)
        VEHICLE.SET_VEHICLE_SIREN(ent, CustomVehicle.siren)
        VEHICLE.SET_VEHICLE_DOORS_LOCKED(ent, CustomVehicle.door_lock_status)
        VEHICLE.SET_VEHICLE_CHEAT_POWER_INCREASE(ent, CustomVehicle.torque)
        VEHICLE.MODIFY_VEHICLE_TOP_SPEED(ent, CustomVehicle.horse_power)
        VEHICLE.SET_VEHICLE_DIRT_LEVEL(ent, CustomVehicle.dirt_level)
        VEHICLE.SET_VEHICLE_LIGHTS(ent, CustomVehicle.lights)
        for i = 0, 6
        do
            if CustomVehicle.open_door[i] then
                VEHICLE.SET_VEHICLE_DOOR_OPEN(ent, i, false, true)
            end
            if CustomVehicle.break_door[i] then
                VEHICLE._SET_VEHICLE_DOOR_CAN_BREAK(ent, i, true)
                VEHICLE.SET_VEHICLE_DOOR_BROKEN(ent, i, true)
            end
        end
    end
    if CustomVehicle.opacity ~= 255 then
        ENTITY.SET_ENTITY_ALPHA(ent, CustomVehicle.opacity, false)
    end
    ENTITY.SET_ENTITY_LOD_DIST(ent, CustomVehicle.lod_dist)
    ENTITY.FREEZE_ENTITY_POSITION(ent, CustomVehicle.freeze)
    ENTITY.SET_ENTITY_COLLISION(ent, CustomVehicle.collision, true)
    ENTITY.SET_ENTITY_VISIBLE(ent, not CustomVehicle.invisible, false)
    if not CustomVehicle.attached then return end
    if new_request[spawn_i][CustomVehicle.attachment.attached_to] == veh then return end -- don't attach to itself
    local found = true
    if not new_request[spawn_i][CustomVehicle.attachment.attached_to] then -- checks if entity for attachment exist
        found = false
        for _, v in ipairs(custom_vehicles.models[id])
        do
            if v.handle_id == CustomVehicle.attachment.attached_to then
                custom_vehicles.spawn(v, spawn_i, pos, id)
                found = true
                break
            end
        end
    end
    if not found then return end
    ENTITY.ATTACH_ENTITY_TO_ENTITY(ent, new_request[spawn_i][CustomVehicle.attachment.attached_to], CustomVehicle.attachment.bone,
        CustomVehicle.attachment.pos.x, CustomVehicle.attachment.pos.y, CustomVehicle.attachment.pos.z,
        CustomVehicle.attachment.pitch, CustomVehicle.attachment.roll, CustomVehicle.attachment.yaw,
        false, true, CustomVehicle.collision, CustomVehicle.type == 1, 2, true
    )
    return ent
end

function custom_vehicles.create(id)
    CreateRemoveThread(true, 'request_model_'..id, function()
        local result = custom_vehicles.request(custom_vehicles.models[id])
        if result == -1 then return 0 end -- invalid model
        if result == 0 then return end -- not loaded
        spawned = spawned + 1
        local spawn_i = spawned
        new_request[spawn_i] = {}
        local pos = features.get_offset_from_player_coords(vector3(0,5,0))
        for _, v in ipairs(custom_vehicles.models[id])
        do
            custom_vehicles.spawn(v, spawn_i, pos, id)
        end
        custom_vehicles.unload(custom_vehicles.models[id])
        local prev_veh = vehicles.get_player_vehicle()
        local velocity
        if settings.Vehicle["SpawnerKeepSpeed"] and settings.Vehicle["SpawnerInside"] and prev_veh ~= NULL then
            velocity = ENTITY.GET_ENTITY_VELOCITY(prev_veh)
        end
        ENTITY.SET_ENTITY_HEADING(new_request[spawn_i].parent, ENTITY.GET_ENTITY_HEADING(PLAYER.PLAYER_PED_ID()))
        if settings.Vehicle["SpawnerKeepSpeed"] and settings.Vehicle["SpawnerInside"] and prev_veh ~= NULL then
            velocity = ENTITY.GET_ENTITY_VELOCITY(prev_veh)
        end
        if settings.Vehicle["SpawnerDeleteOld"] and prev_veh ~= NULL then
            TASK.CLEAR_PED_TASKS_IMMEDIATELY(PLAYER.PLAYER_PED_ID())
            features.delete_entity(prev_veh)
        end
        if velocity then
            ENTITY.SET_ENTITY_VELOCITY(new_request[spawn_i].parent, velocity.x, velocity.y, velocity.z)
        end
        if settings.Vehicle["SpawnerInside"] then
            PED.SET_PED_INTO_VEHICLE(PLAYER.PLAYER_PED_ID(), new_request[spawn_i].parent, -1)
        end
        return 0
    end)
end

return custom_vehicles